FROM nginx

#RUN rm /etc/nginx/conf.d/default.conf

#RUN rm /etc/nginx/conf.d/examplessl.conf

COPY content /usr/share/nginx/html
COPY certs /etc/nginx/certs

RUN chmod -R 777 /usr/share/nginx/html
RUN chmod -R 777 /etc/nginx/certs

EXPOSE 443

RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
