FROM python:3

#set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN  pip install --no-cache-dir -r requirements.txt && apt-get -y update && apt-get -y install uwsgi-plugin-python3

EXPOSE 5000
EXPOSE 3306

# write command for running the application
CMD [ "uwsgi", "--http-socket", ":5000", "--plugin", "python3", "--module", "run:app" ]

